# Generated by Django 5.2.7 on 2025-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_continuetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuetask',
            name='final_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampletask',
            name='final_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
