# Generated by Django 5.2.7 on 2025-10-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_continuetask_final_value_exampletask_final_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContinueTask',
        ),
        migrations.DeleteModel(
            name='ExampleTask',
        ),
    ]
